name: frontend-ci-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  workflow_dispatch:
  pull_request:
    types: [edited]
    branches:
      - main

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: cd starter/frontend && npm ci    
      - run: cd starter/frontend && npm run lint

  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: cd starter/frontend && npm ci
      - run: cd starter/frontend && CI=true npm run test

  build:
    needs: [linting, testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: cd starter/frontend && npm ci
      - run: cd starter/frontend && CI=true npm run test
      - run: |
          cd starter/frontend
          docker build --build-arg=REACT_APP_MOVIE_API_URL="http://a161002e464e04e39a7e327f3fc87350-796166600.us-east-1.elb.amazonaws.com" --tag=mp-frontend:latest .
          docker run --name mp-frontend -p 3000:3000 -d mp-frontend
      

      